name: EC2 Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write
  security-events: write

env:
  AWS_REGION: ap-northeast-2
  TF_VERSION: "1.5.0"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devsecops-k8s/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Cleanup old terraform state
        run: rm -rf .terraform terraform.tfstate* tfplan

      - name: Force init without backend
        run: terraform init -reconfigure -backend=false

      - name: Terraform Plan
        run: terraform plan -lock=false -out=tfplan
        if: github.event_name == 'pull_request'

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -lock=false tfplan

      - name: Generate Terraform outputs
        run: terraform output -json > terraform_outputs.json
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' 