plugin: aws_ec2
regions:
  - ap-northeast-2

filters:
  instance-state-name: running
  tag:Name: webserver*

keyed_groups:
  - key: tags.Name
    prefix: ''
    separator: ''
  - key: tags.Name
    prefix: ''
    separator: ''
    parent_group: webservers

hostnames:
  - tag:Name

compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: "~/.ssh/saju_key"
  ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
