apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SajuAppSecurity
metadata:
  name: saju-app-security-policy
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    labelSelector:
      matchLabels:
        app: "saju-app"
  parameters: {}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PodSecurityPolicy
metadata:
  name: general-pod-security-policy
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
  parameters: {} 