apiVersion: apps/v1
kind: Deployment
metadata:
  name: saju-app
  labels:
    app: saju-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saju-app
  template:
    metadata:
      labels:
        app: saju-app
    spec:
      containers:
      - name: saju-app
        image: 483260554116.dkr.ecr.ap-northeast-2.amazonaws.com/saju-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: RDS_HOST
          valueFrom:
            secretKeyRef:
              name: saju-app-secrets
              key: rds-host
        - name: RDS_USER
          valueFrom:
            secretKeyRef:
              name: saju-app-secrets
              key: rds-user
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saju-app-secrets
              key: rds-password
        - name: RDS_DATABASE
          value: "saju"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: saju-app-secrets
              key: gemini-api-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: saju-app-service
  labels:
    app: saju-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: saju-app
---
apiVersion: v1
kind: Secret
metadata:
  name: saju-app-secrets
type: Opaque
data:
  rds-host: <base64-encoded-rds-host>
  rds-user: YWRtaW4=  # admin
  rds-password: <base64-encoded-password>
  gemini-api-key: <base64-encoded-api-key> 