plugin: aws_ec2
regions:
  - ap-northeast-2

filters:
  instance-state-name: running
  tag:Name: webserver*

keyed_groups:
  - key: tags.Name
    prefix: ''
    separator: ''

hostnames:
  - tag:Name

compose:
  ansible_host: public_ip_address
  ansible_user: >-
    {% if 'amzn' in platform_details|lower or 'amazon' in platform_details|lower %}ec2-user{% else %}ubuntu{% endif %}
  ansible_ssh_private_key_file: "~/.ssh/github_actions_key"
