name: DevSecOps Infrastructure Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm infrastructure deletion'
        required: true
        type: string
        default: ''

env:
  AWS_REGION: us-west-2
  TF_VERSION: "1.5.0"

jobs:
  validate-destroy:
    name: Validate Destroy Confirmation
    runs-on: ubuntu-latest
    
    steps:
    - name: Check confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
          echo "❌ Error: You must type 'DESTROY' to confirm infrastructure deletion"
          echo "This action will permanently delete all AWS resources"
          exit 1
        fi
        echo "✅ Destroy confirmation validated"

  destroy-infrastructure:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    needs: [validate-destroy]
    defaults:
      run:
        working-directory: ./2. devsecops_llm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    
    - name: Terraform Destroy
      run: |
        cd terraform
        echo "🚨 WARNING: This will permanently delete all AWS infrastructure!"
        echo "Destroying DevSecOps infrastructure..."
        terraform destroy -auto-approve

  notify-destroy:
    name: Notify Destroy Completion
    runs-on: ubuntu-latest
    needs: [destroy-infrastructure]
    if: always()
    
    steps:
    - name: Notify on Success
      if: needs.destroy-infrastructure.result == 'success'
      run: |
        echo "✅ DevSecOps infrastructure destroyed successfully!"
        echo "All AWS resources have been removed"
    
    - name: Notify on Failure
      if: needs.destroy-infrastructure.result == 'failure'
      run: |
        echo "❌ DevSecOps infrastructure destruction failed!"
        echo "Please check the logs for details"
        exit 1 