name: DevSecOps Security Scanner

on:
  push:
    branches: [ main, develop ]
    paths:
      - '2. devsecops_llm/**'
  pull_request:
    branches: [ main ]
    paths:
      - '2. devsecops_llm/**'
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Scan type'
        required: true
        default: 'image'
        type: choice
        options:
        - image
        - code
        - full
      target:
        description: 'Target to scan (image name or path)'
        required: false
        default: 'nginx:latest'

env:
  AWS_REGION: us-west-2
  TF_VERSION: "1.5.0"

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2. devsecops_llm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        fi
    
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.48.0
    
    - name: Run Security Scan
      run: |
        if [ "${{ github.event.inputs.scan_type }}" = "image" ]; then
          python generate_security_report.py --image ${{ github.event.inputs.target || 'nginx:latest' }}
        elif [ "${{ github.event.inputs.scan_type }}" = "code" ]; then
          python generate_security_report.py --scan-type code --path ${{ github.event.inputs.target || '.' }}
        else
          python generate_security_report.py
        fi
    
    - name: Upload Security Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: |
          ./2. devsecops_llm/trivy-security-report.md
          ./2. devsecops_llm/*.json
        retention-days: 30

  validate-infrastructure:
    name: Validate Infrastructure Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2. devsecops_llm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
    
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
        terraform validate
    
    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -out=tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: [validate-infrastructure]
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: ./2. devsecops_llm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    
    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve
    
    - name: Save Terraform outputs
      run: |
        cd terraform
        if [ -f "save_outputs.sh" ]; then
          chmod +x save_outputs.sh
          ./save_outputs.sh
        fi

  deploy-application:
    name: Deploy Security Scanner Application
    runs-on: ubuntu-latest
    needs: [deploy-infrastructure]
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: ./2. devsecops_llm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible boto3
    
    - name: Deploy with Ansible
      run: |
        cd ansible
        ansible-playbook -i inventories/aws_ec2.yml playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False

  generate-report:
    name: Generate Security Report
    runs-on: ubuntu-latest
    needs: [security-scan, deploy-application]
    if: always()
    defaults:
      run:
        working-directory: ./2. devsecops_llm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download Security Report
      uses: actions/download-artifact@v4
      with:
        name: security-report
        path: ./2. devsecops_llm
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Generate Final Report
      run: |
        if [ -f "generate_security_report.py" ]; then
          python generate_security_report.py --generate-report
        fi
    
    - name: Upload Final Report
      uses: actions/upload-artifact@v4
      with:
        name: final-security-report
        path: |
          ./2. devsecops_llm/trivy-security-report.md
          ./2. devsecops_llm/*.json
        retention-days: 90

  notify:
    name: Notify Security Scan Results
    runs-on: ubuntu-latest
    needs: [generate-report]
    if: always()
    
    steps:
    - name: Download Final Report
      uses: actions/download-artifact@v4
      with:
        name: final-security-report
        path: ./reports
    
    - name: Notify on Success
      if: needs.generate-report.result == 'success'
      run: |
        echo "✅ DevSecOps security scan completed successfully!"
        echo "Scan type: ${{ github.event.inputs.scan_type || 'full' }}"
        echo "Target: ${{ github.event.inputs.target || 'default' }}"
        if [ -f "./reports/trivy-security-report.md" ]; then
          echo "Security report generated successfully"
        fi
    
    - name: Notify on Failure
      if: needs.generate-report.result == 'failure'
      run: |
        echo "❌ DevSecOps security scan failed!"
        echo "Scan type: ${{ github.event.inputs.scan_type || 'full' }}"
        echo "Target: ${{ github.event.inputs.target || 'default' }}"
        exit 1 